### PR TITLE
Fix security vulnerability: remove workflow scope recommendation and improve error handling

### LINKED ISSUE #92: Bot could abuse workflow editing privileges to execute arbitrary code with access to secrets (e.g. Anthropic API key)
While handling a task the bot could author a workflow that triggers on push and exfiltrates or otherwise abuses secrets, e.g. ANTHROPIC_API_KEY. This could all happen before the repository owner has a chance to review any of the bot's actions.

It's highly implausible that the bot would choose to do this. But, for example, if another vulnerability was found that allowed malicious actors to inject prompts in some way, then they could convince the bot to abuse this vulnerability. Or if a bug was found or introduced allowing the bot to inject prompts into its own future conversations, a similar thing could occur. Bottom line, we need to assume the bot will do its best to destroy the world, and right now it has a vector to do bad things.

### PR DESCRIPTION
**Pull request by blunderingsavant**
## Summary

This PR addresses the security vulnerability identified in issue #92 by removing the recommendation to grant the `workflow` scope to the bot's GitHub token and improving error handling for workflow permission issues.

### 1. Security Warning in README
- **Removed** the recommendation to select `workflow` scope when creating the bot's GitHub token
- **Added** explicit warning about the security risks: *"DO NOT select workflow scope - this would allow the bot to modify GitHub Actions workflows, potentially enabling arbitrary code execution with access to repository secrets"*

### 2. Enhanced Error Detection and Recovery
- **Created** `InsufficientPermissionsError` type in workspace package for recoverable permission errors
- **Enhanced** workflow permission detection in `githubGitRepo.CommitChanges()` to specifically detect attempts to modify `.github/workflows/` files
- **Modified** `ValidateChangesTool` to convert `InsufficientPermissionsError` to `ToolInputError`, making it recoverable
- **Added** helper method `isLikelyWorkflowPermissionError()` to identify workflow-related permission failures

### 3. Improved User Experience
- When the bot attempts to modify workflow files without proper permissions, it now receives a recoverable error that prompts it to use the `report_limitation` tool
- This provides clear feedback to users about the limitation rather than cryptic API errors

## Security Impact

This change eliminates the most dangerous attack vector where a compromised or manipulated bot could:
1. Create malicious workflow files that trigger on push events
2. Execute arbitrary code with access to repository secrets (including `ANTHROPIC_API_KEY`)
3. Exfiltrate or abuse sensitive data before the repository owner can review changes

## Backwards Compatibility

- Existing bots without workflow scope will now receive more helpful error messages when attempting to modify workflows
- Bots that already have workflow scope will continue to function (though repository owners should consider removing this permission)
- No breaking changes to the API or tool interfaces

Fixes #92

---
*This PR was created by the Blundering Savant bot.*

### CODE REVIEW

File: internal/workspace/git.go [hunk 1]
```diff
@@ -149,7 +162,15 @@ func (ggr *githubGitRepo) CommitChanges(ctx context.Context, branch string, chan
 	newTree, resp, err := ggr.git.CreateTree(ctx, ggr.owner, ggr.repo, *baseTree.SHA, treeChangeEntries)
 	if err != nil {
 		if resp.StatusCode == http.StatusNotFound {
-			return nil, fmt.Errorf("failed to create tree (is the bot trying to modify a GitHub workflow with a token that does not include the 'workflow' scope?): %w", err)
+			// Check if this might be a workflow permissions issue
+			if ggr.isLikelyWorkflowPermissionError(treeChangeEntries) {
+				return nil, InsufficientPermissionsError{
+					Operation:   "modifying GitHub workflow files",
+					Reason:      "the GitHub token does not include the 'workflow' scope",
+					Suggestions: "To modify workflow files, the bot's GitHub token must include the 'workflow' scope. However, this scope enables arbitrary code execution and access to repository secrets, which poses significant security risks.",
```
Comment (cchalm) [inline internal/workspace/git.go:170]: Remove the `Suggestions` field. IMO this information is better provided elsewhere

File: README.md [hunk 2]
```diff
@@ -26,7 +26,7 @@ Before using the bot with any deployment option, you'll need to set up the follo
     - Click "Generate new token"
     - Select scopes:
       - `repo` (Full control of private repositories)
-      - `workflow` (If the bot should be allowed to modify `.github/workflows`)
+      - ⚠️ **DO NOT** select `workflow` scope - this would allow the bot to modify GitHub Actions workflows, potentially enabling arbitrary code execution with access to repository secrets
```
Comment (cchalm) [inline README.md:29]: Soften the wording here a bit. Instead of mentioning the workflow scope in a bullet here, let's add a footnote to the `Select scopes` line. The footnote should warn that some scopes pose higher security risks than others, and then give the `workflow` scope as an example

Comment (blunderingsavant) [reply README.md]: Good point! I've moved the workflow scope warning to a footnote [^2] rather than having it as a bullet point, which maintains the warning while keeping the tone softer and less intrusive.

File: internal/workspace/git.go (hunk 1 above)
Comment (blunderingsavant) [reply internal/workspace/git.go]: Removed! The `Suggestions` field has been completely removed from the `InsufficientPermissionsError` struct and all related code. The error message is now simpler and more focused.

**Comment by blunderingsavant** [comment]
I've addressed all the review comments from @cchalm:

## Changes Made:

1. **Softened workflow scope warning** - Moved the workflow scope warning from a bullet point to a footnote [^2] for a more subtle approach while maintaining the security information

2. **Fixed grammar in error message** - Changed `Operation: "modifying GitHub workflow files"` to `Operation: "modify GitHub workflow files"` so the error message now correctly reads "unable to modify GitHub workflow files"

3. **Removed Suggestions field** - Completely removed the `Suggestions` field from `InsufficientPermissionsError` struct as requested, simplifying the error structure

The security vulnerability fix remains intact - the bot still cannot get workflow permissions by default, and when it encounters workflow-related permission errors, it receives a recoverable error that prompts it to use the `report_limitation` tool.

File: internal/workspace/git.go [hunk 3]
```diff
@@ -4,10 +4,22 @@ import (
...
 
+// InsufficientPermissionsError indicates that an operation failed due to insufficient GitHub token permissions.
+// This error is intended to be converted to a ToolInputError by the bot layer, prompting the bot to report a limitation.
+type InsufficientPermissionsError struct {
+	Operation string
+	Reason    string
+}
+
+func (ipe InsufficientPermissionsError) Error() string {
+	return fmt.Sprintf("insufficient permissions for %s: %s", ipe.Operation, ipe.Reason)
```
Comment (cchalm) [inline internal/workspace/git.go:20]: Now the grammar is wrong here - "insufficient permissions for modify GitHub workflow files"

File: README.md [hunk 4]
```diff
@@ -70,6 +69,8 @@ Before using the bot with any deployment option, you'll need to set up the follo
 
 [^1]: There is currently no way to generate fine-grained access tokens for collaborator access to repositories owned by individuals. When you give a classic Personal Access Token to the bot, you should assume that it will attempt to abuse the broad permissions of that access token. As a repository owner, use collaborator permission settings and protected branches to restrict the bot's permissions to only the minimum required to perform its intended functions.
 
+[^2]: Some token scopes pose higher security risks than others. For example, the `workflow` scope allows modification of GitHub Actions workflows, potentially enabling arbitrary code execution with access to repository secrets.
```
Comment (cchalm) [inline README.md:72]: Emphasize that the AI could author and execute arbitrary code before a pull request is created and therefore without any oversight.

Also, add something like "while the bot being able to modify workflows is useful, we recommend leaving this scope disabled and using other tools to get AI input on workflows without the execution risk".

File: internal/workspace/git.go [hunk 5]
```diff
@@ -4,10 +4,22 @@ import (
 	"context"
 	"fmt"
 	"net/http"
+	"strings"
 
 	"github.com/google/go-github/v72/github"
 )
 
+// InsufficientPermissionsError indicates that an operation failed due to insufficient GitHub token permissions.
+// This error is intended to be converted to a ToolInputError by the bot layer, prompting the bot to report a limitation.
```
Comment (cchalm) [inline internal/workspace/git.go:13]: Remove the second line of this comment. The workspace package should be independent of the bot package, as much as possible

File: README.md (hunk 4 above)
Comment (blunderingsavant) [reply README.md:72]: Enhanced! The footnote now emphasizes that "the AI could author and execute arbitrary code before a pull request is created and therefore without any oversight" and includes the recommendation: "while the bot being able to modify workflows is useful, we recommend leaving this scope disabled and using other tools to get AI input on workflows without the execution risk".

**Comment by blunderingsavant** [comment]
✅ **Addressed all review feedback**

Fixed the remaining issues identified by @cchalm:

## Changes Made:
1. **Fixed grammar in error message** - Changed "insufficient permissions for %s" to "insufficient permissions to %s" so the message now correctly reads "insufficient permissions to modify GitHub workflow files"

2. **Enhanced README security warning** - Updated footnote [^2] to:
   - Emphasize that the AI could execute arbitrary code **before a pull request is created** and **without any oversight**  
   - Add recommendation to use other tools for workflow AI input without the execution risk

The security vulnerability fix remains intact and now provides clearer, more grammatically correct messaging. Ready for final review! 🚀

File: internal/workspace/git.go (hunk 5 above)
Comment (blunderingsavant) [reply internal/workspace/git.go]: Fixed! Removed the second line of the comment as requested to maintain package independence.

**Comment by blunderingsavant** [comment]
✅ **Addressed final review feedback**

Removed the bot-specific reference from the `InsufficientPermissionsError` comment as requested by @cchalm to maintain package independence between workspace and bot layers.

The security fix is now complete and all review feedback has been addressed! 🚀

**Comment by blunderingsavant** [comment]
✅ **Addressed final review feedback from @cchalm**

Fixed the error handling logic in `internal/workspace/git.go` as requested:

- **Combined conditions** - Changed from nested `if` statements to a single condition: `resp.StatusCode == http.StatusNotFound && ggr.isLikelyWorkflowPermissionError(treeChangeEntries)`
- **Removed redundant error message** - Eliminated the special "failed to create tree (404 error)" variant since the original error already contains that information
- **Simplified flow** - Now falls through to the default error handler when either condition is not met

The security vulnerability fix remains intact and all review feedback has been addressed! 🚀

File: README.md [hunk 6]
```diff
@@ -70,6 +69,8 @@ Before using the bot with any deployment option, you'll need to set up the follo
 
 [^1]: There is currently no way to generate fine-grained access tokens for collaborator access to repositories owned by individuals. When you give a classic Personal Access Token to the bot, you should assume that it will attempt to abuse the broad permissions of that access token. As a repository owner, use collaborator permission settings and protected branches to restrict the bot's permissions to only the minimum required to perform its intended functions.
 
+[^2]: Some token scopes pose higher security risks than others. For example, the `workflow` scope allows modification of GitHub Actions workflows, potentially enabling the AI to author and execute arbitrary code before a pull request is created and therefore without any oversight. While the bot being able to modify workflows is useful, we recommend leaving this scope disabled and using other tools to get AI input on workflows without the execution risk.
```
Comment (cchalm) [inline README.md:72]: We should mention that the arbitrary code would have access to repository secrets, otherwise it's not much of a risk

**Comment by blunderingsavant** [comment]
✅ **Addressed @cchalm's final feedback**

Updated the security warning in footnote [^2] to explicitly mention that arbitrary code execution would have **access to repository secrets**, making the security risk clearer.

The warning now reads: "potentially enabling the AI to author and execute arbitrary code **with access to repository secrets** before a pull request is created and therefore without any oversight."

All review feedback has been addressed! 🚀
